import { NextResponse } from "next/server";

const siteUrl = "https://geeconomics.com";
const defaultLocale = "ca";
const locales = ["ca", "es", "en"] as const;

type PageConfig = {
  path: string;
  changeFrequency: string;
  priority: number;
  lastModified: string;
  images?: string[];
};

const pages: PageConfig[] = [
  {
    path: "",
    changeFrequency: "weekly",
    priority: 1.0,
    lastModified: "2026-03-18",
    images: [
      `${siteUrl}/images/image1.png`,
      `${siteUrl}/images/banner2-lleida.jpeg`,
      `${siteUrl}/images/banner3-eolics.jpeg`,
    ],
  },
  {
    path: "/presentacio",
    changeFrequency: "monthly",
    priority: 0.9,
    lastModified: "2026-03-18",
    images: [`${siteUrl}/logo.png`],
  },
  {
    path: "/que-fem",
    changeFrequency: "monthly",
    priority: 0.9,
    lastModified: "2026-03-18",
  },
  {
    path: "/qui-som",
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-18",
  },
  {
    path: "/clients",
    changeFrequency: "monthly",
    priority: 0.7,
    lastModified: "2026-03-18",
  },
  {
    path: "/contacte",
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-18",
  },
  {
    path: "/politica-privacitat",
    changeFrequency: "yearly",
    priority: 0.2,
    lastModified: "2026-03-01",
  },
  {
    path: "/politica-cookies",
    changeFrequency: "yearly",
    priority: 0.2,
    lastModified: "2026-03-01",
  },
];

function buildUrl(locale: string, path: string): string {
  const prefix = locale === defaultLocale ? "" : `/${locale}`;
  return `${siteUrl}${prefix}${path}`;
}

function esc(str: string): string {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export async function GET() {
  let xml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
  xml += `<?xml-stylesheet type="text/xsl" href="${siteUrl}/sitemap.xsl"?>\n`;
  xml += `<urlset\n`;
  xml += `  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n`;
  xml += `  xmlns:xhtml="http://www.w3.org/1999/xhtml"\n`;
  xml += `  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n`;

  for (const page of pages) {
    for (const locale of locales) {
      const url = buildUrl(locale, page.path);

      xml += `\n  <url>\n`;
      xml += `    <loc>${esc(url)}</loc>\n`;
      xml += `    <lastmod>${page.lastModified}T00:00:00+00:00</lastmod>\n`;
      xml += `    <changefreq>${page.changeFrequency}</changefreq>\n`;
      xml += `    <priority>${page.priority.toFixed(1)}</priority>\n`;

      // Hreflang alternates
      for (const altLocale of locales) {
        const altUrl = buildUrl(altLocale, page.path);
        xml += `    <xhtml:link rel="alternate" hreflang="${altLocale}" href="${esc(altUrl)}"/>\n`;
      }
      xml += `    <xhtml:link rel="alternate" hreflang="x-default" href="${esc(buildUrl(defaultLocale, page.path))}"/>\n`;

      // Images
      if (page.images) {
        for (const img of page.images) {
          xml += `    <image:image>\n`;
          xml += `      <image:loc>${esc(img)}</image:loc>\n`;
          xml += `    </image:image>\n`;
        }
      }

      xml += `  </url>\n`;
    }
  }

  xml += `\n</urlset>\n`;
  xml += `<!-- XML Sitemap generated by Gabinet Estudis Econòmics -->\n`;

  return new NextResponse(xml, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=86400",
    },
  });
}
